### ISSUE TITLE
Installation instructions out of date?

### ISSUE THREAD

**Issue by mdboom** [myuhe/org-wunderlist.el#4]
Following the installation instructions in the README, I go to the "My Apps" page and click on "Create An App", but the next form requires an "Auth Callback URL" in order to get the credentials.  What do I enter into this field and/or how do I get the auth tokens?

**Comment by zobi8225** [comment]
+1

**Comment by thomas-louvigne** [comment]
You can put absurd website, it's work.

**Comment by myuhe** [comment]
Fix doc. https://github.com/myuhe/org-wunderlist.el/commit/b89633fcfd74e83dd8a5d81619244a666a45715c

Thanks :+1:
